### PR TITLE
852 analytical frequency curve should plot on normal probability axis

### PR DESCRIPTION
**Pull request by Brennan1994**

### CODE REVIEW

**Comment by Brennan1994** [comment]
image

**Comment by rnugent3** [comment]
I am not able to edit a graphical frequency function - I hit an overflow exception. 

image

```
 at System.Convert.ToInt64(Double value)
   at Statistics.Histograms.Histogram.AddObservationToHistogram(Double observation, Int64 index) in C:\Code\C#\FDA\HEC-FDA\HEC.FDA.Statistics\Histograms\Histogram.cs:line 385
   at HEC.FDA.Model.extensions.ContinuousDistributionExtensions.BootstrapToUncertainPairedData(ContinuousDistribution continuousDistribution, IProvideRandomNumbers randomProvider, Double[] ExceedanceProbabilities, Int32 realizations, Double histogramBinWidth) in C:\Code\C#\FDA\HEC-FDA\HEC.FDA.Model\extensions\ContinuousDistributionExtensions.cs:line 42
   at HEC.FDA.ViewModel.FrequencyRelationships.AnalyticalFrequencyEditorVM.GetCoordinatesFunction() in C:\Code\C#\FDA\HEC-FDA\HEC.FDA.ViewModel\FrequencyRelationships\AnalyticalFrequencyEditorVM.cs:line 391
   at HEC.FDA.ViewModel.FrequencyRelationships.AnalyticalFrequencyEditorVM.UpdateChartLineData() in C:\Code\C#\FDA\HEC-FDA\HEC.FDA.ViewModel\FrequencyRelationships\AnalyticalFrequencyEditorVM.cs:line 318
   at HEC.FDA.View.FrequencyRelationships.AnalyticalFrequencyEditor.rad_standard_Checked(Object sender, RoutedEventArgs e) in C:\Code\C#\FDA\HEC-FDA\HEC.FDA.View\FrequencyRelationships\AnalyticalFrequencyEditor.xaml.cs:line 82
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.RadioButton.OnChecked(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ToggleButton.OnIsCheckedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by rnugent3** [comment]
the bug is not confined to this branch - the bug is on main, too. I will set up an issue for the bug.

**Review by rnugent3 — APPROVED** [review]
Looks great

**Pull request merged**
