### PR TITLE
Fix alt comp labels

### PR DESCRIPTION
**Pull request by Brennan1994**

### CODE REVIEW

**Review by rnugent3 — CHANGES_REQUESTED** [review]
The y-axis label change caused a change in the table label and plot title of the alternative results. The alternative comparison results report looks good - just alternative results needs an update, please. 

Alternative results on this branch: 
image

Alternative results on main: 
image

**Review by rnugent3 — CHANGES_REQUESTED** [review]
Please grab the chart title, too? 

image

**Comment by Brennan1994** [comment]
Ok, Final Pass. I'd bet a intoxicating beverage of your choice on it. 
Scenarios:
image
Alternative:
image
Alternative Comps:
image
image

**Comment by Brennan1994** [comment]
Merging without final review. Main will need to be reviewed before release to confirm labels are correct. This lets me keep moving on creating a release package, and is ultimately an improvement on the errors in labels in main currently.

**Pull request merged**
