### PR TITLE
956 UI updates

### PR DESCRIPTION
**Pull request by codymccoy**
this should complete issue #963

### CODE REVIEW

**Comment by rnugent3** [comment]
@codymccoy I have one tiny request. when the checkbox is not marked, could the stage-damage combo box label be "Stage-Damage" while if the checkbox is marked, let the combo box label be "Failure Stage-Damage"

**Comment by rnugent3** [comment]
Otherwise, the UI edits look good to me. I've not yet run because we're not yet hooked up. @Brennan1994 would you mind taking a look at the code changes?

**Comment by codymccoy** [comment]
Sure, i can make that change.

**Comment by codymccoy** [comment]
I just pushed the requested label change. I also moved the red stars down a bit on the new stage damage row.

**Review by Brennan1994 — APPROVED** [review]

**Pull request merged**
