### PR TITLE
now plots directly the input lp3. includes tests to validate prior behavior.

### PR DESCRIPTION
**Pull request by Brennan1994**

### CODE REVIEW

**Review by rnugent3 — CHANGES_REQUESTED** [review]
I have reviewed, and made two small edits: I added the quantity of realizations for the parametric bootstrap and fixed a comment. 

The user interface still needs work. See the image below. Two things: 
1. Please change the "Mean" label to "Discharge" 
2. inputLP3asUPD is correct, but is not showing up in the user interface. 

image

**Comment by rnugent3** [comment]
The following table contains the correct discharges of the input function for the west sac analytical flow-frequency function: 

Frequency | Flow | Stage
-- | -- | --
0.5 | 202306 | 23.86
0.2 | 373981 | 27.38
0.1 | 508002 | 29.5
0.04 | 696277 | 31.66
0.02 | 848335 | 33.04
0.01 | 1009190 | 34.58
0.005 | 1179084 | 36.11
0.002 | 1417793 | 37.58


I see the discharges in the above table within inputFunction, it seems like inputFunction is not making it to the user interface

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/9c73650bfc2d259b56e75dfe58e2ac1f1532b970/HEC.FDA.ViewModel/TableWithPlot/Base/BaseLP3TableWithPlot.cs#L71

**Comment by Brennan1994** [comment]
image

**Review by rnugent3 — APPROVED** [review]
Works great! Thanks, @Brennan1994

**Pull request merged**
