### PR TITLE
Scenario threshold 820

### PR DESCRIPTION
**Pull request by codymccoy**
Several github issues completed in this PR.

### CODE REVIEW

**Comment by Brennan1994** [comment]
Was this known to break backward compatability? I'm getting tons of exceptions loading old studies. I wrapped the following code in a try catch

**Review by Brennan1994 — APPROVED** [review]

**Review by rnugent3 — CHANGES_REQUESTED** [review]
Stellar work!! I have a few requests for changes - some small UI stuff. 
image
image
image

**Comment by codymccoy** [comment]
Threshold stage label updated:
image

I added a min width to these combos so that they look better when nothing is in them:
image

**Comment by codymccoy** [comment]
The value gets set when the lateral structure is selected and goes back to zero when the blank option is selected. 
image

When there is a lateral structure then the checkbox is disabled:
image

**Pull request merged**
