### PR TITLE
added stack trace to stage damage exception catch

### PR DESCRIPTION
**Pull request by rnugent3**
teeny tiny change

### CODE REVIEW

**Comment by rnugent3** [comment]
I broke something in view results...please hold off review

**Comment by rnugent3** [comment]
This PR also includes the code required to report progress on stage damage functions from the model, and a couple format changes

**Comment by rnugent3** [comment]
@Brennan1994 this is ready for your review

**Comment by rnugent3** [comment]
still broken

**Comment by rnugent3** [comment]
When we do not have any structures in a given impact area, we do not produce stage-damage functions. However, it is perfectly reasonable that we need stage damage functions that have zero damage for comparison with stage damage that has positive damage if an impact area is being bought out

**Comment by rnugent3** [comment]
I need to add validation to make sure that an impact area scenario either has minimally stage-damage functions or a levee

**Review by Brennan1994 — APPROVED** [review]

**Pull request merged**
